# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Will\OneDrive - Middlesex University\Inventions\fanatec wheel\wheel rev 3\wheelDashboard\designer\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, time
from socket import *
from struct import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QRunnable, Qt, QThreadPool

class Runnable(QRunnable):
    def __init__(self):
        super().__init__()

    
    def run(self):
        self.initialiseUDPCon()
        while True:
            self.pktformat='cifff??????fffiiiifffffiffffffffffffffffff'
            self.messageback, self.ipAddress =self.clientSocket.recvfrom(16384)
            self.backString = unpack(self.pktformat, self.messageback[:152])

            self.gear = self.backString[23]
            self.speed = self.backString[3]

            if (self.gear > 1):
                self.gearFinal = self.gear - 1

            if (self.gear == 1):
                self.gearFinal = "N"

            if (self.gear == 0):
                self.gearFinal = "R"

            self.speedFinal = round(self.speed)

            window.gearLabel.setText(str(self.gearFinal))
            window.speedLabel.setText(str(self.speedFinal))

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(720, 720)
        MainWindow.setMinimumSize(QtCore.QSize(720, 720))
        MainWindow.setMaximumSize(QtCore.QSize(720, 720))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setToolTipDuration(7)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 720, 720))
        self.graphicsView.setStyleSheet("background-image: url(C:/Users/Will/OneDrive - Middlesex University/Inventions/fanatec wheel/wheel rev 3/wheelDashboard/dashBackground.png); background-repeat: no-repeat; background-position: center;")
        self.graphicsView.setObjectName("graphicsView")
        self.speedLabel = QtWidgets.QLabel(self.centralwidget)
        self.speedLabel.setGeometry(QtCore.QRect(360, 312, 151, 61))
        
        self.fonts()

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.speedLabel.setText(_translate("MainWindow", "0"))

    def fonts(self):
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        self.speedLabel.setFont(font)
        self.speedLabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.speedLabel.setStyleSheet("color:rgb(255,255,255)")
        self.speedLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.speedLabel.setMidLineWidth(-1)
        self.speedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.speedLabel.setObjectName("speedLabel")

    def runTasks(self):
            threadCount = QThreadPool.globalInstance().maxThreadCount()
            pool = QThreadPool.globalInstance()
            runnable = Runnable()
            pool.start(runnable)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.runTasks()
    MainWindow.show()
    sys.exit(app.exec_())
